# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
    - main
    - master
    - release/*
  schedule:
    - cron: "0 * * * 1-5" 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: tree
        run: brew install tree
        
      - name: rm files
        run: |
           shopt -s extglob
           rm -rf !(@(.git|.github))
     
      - name: download
        run: |
           git clone https://github.com/autoasset/Khala project
           tree -a
           rm -rf project/.git
           rm -rf project/.github
           rm -rf project/.gitignore 
           rsync -aP project/. ./
           rm -rf project

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
          
      - name: yarn-install
        run: yarn install
        
      - name: tsc
        run: tsc -p .
              
       - name: tree
        run: tree -a

      - name: build
        run: yarn build

      - name: Commit
        run: |
          git config --global user.name 'linhey'
          git config --global user.email 'is.linhey@outlook.com'
          git pull
          git commit -am "sync"
          git push
